# Generated by Django 3.1.6 on 2021-02-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Пометка удаления')),
                ('status', models.IntegerField(choices=[(None, '(Не известно)'), (0, 'Новый'), (1, 'Готов '), (2, 'Доставлен'), (3, 'Отменен')], default=0, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Внесено')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='К внесению')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальный остаток')),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Конечный остаток')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Внесено')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='К внесению')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник заказа',
                'verbose_name_plural': 'Участники заказа',
                'db_table': 'order_partners',
                'unique_together': {('partner', 'order')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='partners',
            field=models.ManyToManyField(through='orders.OrderPartner', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
