# Generated by Django 3.1.6 on 2021-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='К внесению'),
        ),
        migrations.AlterField(
            model_name='order',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Внесено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Конечный остаток'),
        ),
        migrations.AlterField(
            model_name='order',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начальный остаток'),
        ),
        migrations.AlterField(
            model_name='orderpartner',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='К внесению'),
        ),
        migrations.AlterField(
            model_name='orderpartner',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Внесено'),
        ),
    ]
