# Generated by Django 3.1.6 on 2021-02-08 14:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orders', '0002_auto_20210208_1743'),
    ]

    operations = []
