# Generated by Django 3.1.6 on 2021-02-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210208_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prevent_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
