# Generated by Django 3.1.6 on 2021-02-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210209_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='credit',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(None, '(Не известно)'), (0, 'Новый'), (1, 'Готов'), (2, 'Доставлен'), (3, 'Отменен')], default=0, verbose_name='Статус'),
        ),
    ]
