# Generated by Django 4.0.2 on 2023-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpartner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderpartner',
            table=None,
        ),
    ]
