# Generated by Django 4.2 on 2023-04-26 07:13

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderpartner_id_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='Список товаров заказа', verbose_name='Содержание'),
        ),
    ]
